### ISSUE TITLE
White screen after theme install

### ISSUE THREAD

**Issue by JuliaRietveld** [KnowTheCode/KTC-Child-Theme#1]
Hallo Tonya,
After I install this theme and activate it, I see a white screen. I'm using the latest Genesis version. And if I put `die( 'it is loading' );` in functions.php I do get this message. 

Please, help!

Thank you

**Comment by hellofromtonya** [comment]
We added more dependencies to this theme in our latest update.  We are using multiple functions from Fulcrum and Help Center plugins.  To help you out and anyone else who want to use this theme, I added a `lib/support/dependencies-helpers.php` file.  This file loads in dummy functionality that works in place of Fulcrum and Help Center.

For your project, you should not need these dependencies.  Help Center is a specific implementation for Know the Code.  Fulcrum is a central repository for building add-on plugins.  This new dependencies helper file eliminates the need for loading either of these plugins.

You will need to pull down the latest changes for this theme's repository.

**Comment by JuliaRietveld** [comment]
Hallo Tonya, I just pulled your today's commit and added this theme to my local WP. The white screen is now not only on front end but also in the admin of WP as well. What am I doing wrong? In my 'themes' folder I only have Genesis en KCT, in 'plugins' only Akismet en Pods. 
Thank you so much for your answer! I LOVE your video's. No one, not even Genesis self makes such a clean and structured code.

**Comment by hellofromtonya** [comment]
Let's walk through the problem step-by-step.
1. Delete the theme from the `wp-content/themes/` folder.  Let's remove it.
2. Now you should be able to change the theme in `Appearance > Theme` to say Genesis.
3. In doing so, can you load the front-end?  Or do you have the same issue?  
   a. If the same issue, then switch to one of the default WordPress themes.  If the problem goes away, redownload Genesis.
   b. If problem went away when switching to Genesis framework only, go to the next step.
4.  Now, clone the new KTC theme into the themes folder. 
5. Rename it to `ktc`.
6. Go and activate the theme in `Appearance > Theme`.  Is the problem gone? Or did it resurface again?

**Comment by JuliaRietveld** [comment]
1. check
2. check
3. check, everything is working fine
4. check
5. check
6. check. I activate the theme and get the white screen. I tried the front end and the admin. All white.

**Comment by hellofromtonya** [comment]
And what version of PHP are you using?  It needs to be 5.4 or greater.

**Comment by JuliaRietveld** [comment]
7.0.12

**Comment by hellofromtonya** [comment]
Next let's do some debugging together to find out what is causing an issue in your system. As you do each item, check if the white screen goes away.  If it does, then move on to the next one.  If it doesn't, that the problem lies in this step.
1. In `functions.php`, comment out line 15, i.e. `//require_once( 'lib/support/autoload.php' );`.
2. Uncomment #1. Then in `lib/support/autoload.php`  on line 51, add the following: `var_dump( $folder_root ); die();`.  Is the folder root correct?  It should be pointing to the `{your full path}/wp-content/themes/ktc/lib/`.
3. Remove the temporary code from #2 above. Let's narrow down which file is causing it.  In the function `init_files()`, comment out lines 27-32.  In doing so, none of the `structure` files will load.  

Refresh and let me know which step has the problem returning.

**Comment by JuliaRietveld** [comment]
1. site came back but I lost the stylesheet. (not important)
2. the path is correct.
3. you mean lines 26 - 31? Line 32 is the closing ); Here it went white again.

Thank you so much, you are amazing!

**Comment by hellofromtonya** [comment]
1. Yes you would because we are not loading that yet.
2. Good.
3. Sorry, lines 26 to 31 [shown here](https://github.com/KnowTheCode/KTC-Child-Theme/blob/master/lib/support/autoload.php#L26)

**Comment by hellofromtonya** [comment]
Great big apologies coming your way.... I forgot to commit this [line of code](/Users/hellofromtonya/Sites/knowthecode.dev/wp-content/themes/ktc) into the repository. This line of code autoloads the new plugin dependencies helper file.  You need that one. I'm slapping myself as I write this.....sorry about that.
